"""Generate wiki/index.txt — AI-facing full catalog of all wiki pages.

人間向けの curated navigation は wiki/index.md。AI / LLM がナビゲーションに使う
フルカタログはこちらの index.txt にまとめる。frontmatter の summary をそのまま
出力するので、ページを増やすたびに本スクリプトで regenerate する。

Usage: python3 scripts/build_index_txt.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

WIKI = Path(__file__).parent.parent / "wiki"
OUTPUT = WIKI / "index.txt"
FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)

TYPE_ORDER = {"concept": 0, "entity": 1, "source": 2, "analysis": 3}


def load_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER.match(text)
    if not m:
        return {}
    try:
        parsed = yaml.safe_load(m.group(1)) or {}
    except Exception:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def main() -> int:
    entries: list[tuple[int, str, str, str, str]] = []
    for path in sorted(WIKI.rglob("*.md")):
        if path.name in ("index.md", "log.md"):
            continue
        rel = path.relative_to(WIKI).as_posix()
        fm = load_frontmatter(path)
        typ = str(fm.get("type", "?")).strip() or "?"
        summary = str(fm.get("summary", "")).strip().replace("\n", " ")
        order = TYPE_ORDER.get(typ, 99)
        entries.append((order, typ, rel, path.stem, summary))

    lines = [
        "# wiki/index.txt — AI 向けフルカタログ (auto-generated by scripts/build_index_txt.py)",
        "# 人間向け curated navigation は index.md。本ファイルは AI が grep / 一覧読みするための物。",
        "# Format: <stem>\\t<type>\\t<path>\\t<summary>",
        "# Regenerate: python3 scripts/build_index_txt.py",
        "",
    ]
    for _, typ, rel, stem, summary in sorted(entries, key=lambda e: (e[0], e[2])):
        lines.append(f"{stem}\t{typ}\t{rel}\t{summary}")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(entries)} pages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
