"""Refresh wiki/log.txt (AI compact full history) and wiki/log.md (human recent 7 days).

- log.md = 直近 7 日の entry を newest-first で full detail
- log.txt = 全 entry の compact 1 行表現 (auto-generated)
- lint type entry は両方から除外（無検出 lint は記録対象外）
- log.md から落ちた古い entry の詳細は git log で参照

Idempotent: 任意のタイミングで実行できる。既存 log.txt との merge により、
古い entry も log.txt には保持される。

Usage: python3 scripts/refresh_logs.py
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

WIKI = Path(__file__).parent.parent / "wiki"
LOG_MD = WIKI / "log.md"
LOG_TXT = WIKI / "log.txt"
RECENT_DAYS = 7

HEADER = re.compile(
    r"^## \[(\d{4}-\d{2}-\d{2})(?: (\d{2}:\d{2}))?\] ([a-z-]+) \| (.+)$"
)


def parse_md(path: Path) -> list[tuple[str, str, str, str]]:
    """Return list of (ts, type, title, body) tuples in document order.

    ts is "YYYY-MM-DD HH:MM"; if header had no time, fills "23:59" (CLAUDE.md 後方互換).
    body is the full text below the header up to (but excluding) the next header.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)

    entries: list[tuple[str, str, str, str]] = []
    current: tuple[str, str, str, list[str]] | None = None
    for line in lines:
        m = HEADER.match(line.rstrip("\n"))
        if m:
            if current is not None:
                ts, typ, title, buf = current
                entries.append((ts, typ, title, "".join(buf).rstrip("\n")))
            date, time, typ, title = m.groups()
            ts = f"{date} {time or '23:59'}"
            current = (ts, typ, title, [])
        elif current is not None:
            current[3].append(line)
    if current is not None:
        ts, typ, title, buf = current
        entries.append((ts, typ, title, "".join(buf).rstrip("\n")))
    return entries


def parse_txt(path: Path) -> list[tuple[str, str, str]]:
    """Return list of (ts, type, title) from existing log.txt."""
    if not path.exists():
        return []
    out: list[tuple[str, str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t", 2)
        if len(parts) == 3:
            out.append((parts[0], parts[1], parts[2]))
    return out


def main() -> int:
    md_entries = parse_md(LOG_MD)
    txt_entries = parse_txt(LOG_TXT)

    # Filter lint entries — 無検出 lint は記録対象外、検出ありの場合は filing-back で書く運用
    md_kept = [e for e in md_entries if e[1] != "lint"]
    lint_dropped_md = len(md_entries) - len(md_kept)
    txt_kept = [e for e in txt_entries if e[1] != "lint"]

    # Merge for log.txt: dedup by (ts, type, title), prefer md (latest authoritative source)
    keyset: dict[tuple[str, str, str], None] = {}
    for ts, typ, title, _body in md_kept:
        keyset[(ts, typ, title)] = None
    for ts, typ, title in txt_kept:
        keyset.setdefault((ts, typ, title), None)

    all_keys = sorted(keyset.keys(), key=lambda k: k[0], reverse=True)

    # Write log.txt
    txt_lines = [
        "# wiki/log.txt — AI 向けフル作業履歴 (auto-generated by scripts/refresh_logs.py)",
        "# 人間向け直近 7 日分は log.md。古い entry の詳細は git log -- wiki/log.md で参照",
        "# Format: <YYYY-MM-DD HH:MM>\\t<type>\\t<title>",
        "# Regenerate: python3 scripts/refresh_logs.py",
        "",
    ]
    for ts, typ, title in all_keys:
        txt_lines.append(f"{ts}\t{typ}\t{title}")
    LOG_TXT.write_text("\n".join(txt_lines) + "\n", encoding="utf-8")

    # Compute 7-day cutoff (relative to newest entry, not now — keeps reproducible on
    # quiet days)
    if md_kept:
        newest_ts = max(e[0] for e in md_kept)
        newest_dt = datetime.strptime(newest_ts, "%Y-%m-%d %H:%M")
        cutoff_dt = newest_dt - timedelta(days=RECENT_DAYS)
    else:
        cutoff_dt = datetime.min

    # log.md keeps entries with ts >= cutoff, newest first
    recent = [
        (ts, typ, title, body)
        for (ts, typ, title, body) in md_kept
        if datetime.strptime(ts, "%Y-%m-%d %H:%M") >= cutoff_dt
    ]
    recent.sort(key=lambda e: e[0], reverse=True)

    md_lines = [
        "# Log",
        "",
        f"> 直近 {RECENT_DAYS} 日分のみ。全件 compact 履歴は [log.txt](log.txt)、それより古い entry の詳細は `git log -- wiki/log.md` で参照。",
        f"> 更新は `python3 scripts/refresh_logs.py` で log.txt と log.md を再生成する。",
        "",
    ]
    for ts, typ, title, body in recent:
        md_lines.append(f"## [{ts}] {typ} | {title}")
        if body.strip():
            md_lines.append("")
            md_lines.append(body.rstrip())
        md_lines.append("")
    LOG_MD.write_text("\n".join(md_lines).rstrip() + "\n", encoding="utf-8")

    dropped_old = len(md_kept) - len(recent)
    print(
        f"log.txt: {len(all_keys)} entries\n"
        f"log.md: {len(recent)} entries (cutoff {cutoff_dt:%Y-%m-%d %H:%M}, dropped {dropped_old} old + {lint_dropped_md} lint)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
